# Generated by Django 5.1.3 on 2024-11-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='id',
            new_name='ide',
        ),
    ]
